install.packages("tidyverse")
install.packages("FactoMineR")
install.packages("SensoMineR")
install.packages("remotes")
library(remotes)
remotes::install_github("cbail/textnets", dependencies = TRUE)
remotes::install_github("MaximeSaland/YesSiR")