install.packages("FactoMineR")
install.packages("devtools")
library(devtools)
install.packages("remotes")
library(remotes)
remotes::install_github("cbail/textnets")
remotes::install_github("MaximeSaland/YesSiR")